// <auto-generated />
using System;
using DotNetCoreAngular.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotNetCoreAngular.Persistence.Migrations
{
    [DbContext(typeof(DotNetCoreAngularDbContext))]
    [Migration("20200414111217_AddedDefaultGridPageSizeColumn")]
    partial class AddedDefaultGridPageSizeColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("DotNetCoreAngular.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshTokenExpDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserExtensionsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserExtensionsId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DotNetCoreAngular.Domain.Entities.UserExtensions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultGridPageSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Theme")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserExtensions");
                });

            modelBuilder.Entity("DotNetCoreAngular.Domain.Entities.User", b =>
                {
                    b.HasOne("DotNetCoreAngular.Domain.Entities.UserExtensions", "UserExtensions")
                        .WithMany("Users")
                        .HasForeignKey("UserExtensionsId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
